name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '21' ]
    name: Java ${{ matrix.Java }} test and verify
    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: '5'
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Cache NVD Database
        id: cache-nvd
        uses: actions/cache/restore@v5
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: nvd-cache-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            nvd-cache-${{ runner.os }}-

      - name: Get Versions
        run: |
          echo "Google chrome version"
          google-chrome --version
          echo "firefox version"
          firefox --version
          echo "temp folder: ${{ runner.temp }}"

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify -Djava.io.tmpdir=${{ runner.temp }}
        env:
            NVD_NIST_APIKEY: ${{ secrets.NVD_NIST_APIKEY}}

      - name: Package artifacts
        run: |
         mkdir staging
         cp -rf target/*.jar staging
         cp -rf target/*reports staging

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: Package
          path: staging
          overwrite: true

      - name: Cache NVD Database
        uses: actions/cache/save@v5
        if: ${{ always() }}
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: nvd-cache-${{ runner.os }}-${{ github.run_id }}

